### ISSUE TITLE
AttributeError: 'module' object has no attribute 'umr_sum'

### ISSUE THREAD

**Issue by lim643** [mehrdadn/SOTA-Py#2]
Hi,

I tried to run your program using the terminal command that you provided:

python Main.py --source=65280072.0 --dest=65345534.0 --budget=1800 --network="data/sf.osm.json"

But I got the following error message:

Importing numpy... 139 ms
Importing scipy.special... 19 ms
Importing numba... 0 ms
Other imports... Traceback (most recent call last):
  File "Main.py", line 391, in <module>
    class PolicyGUIUpdater(object):
  File "Main.py", line 402, in PolicyGUIUpdater
    def update(self, tinow={}.get(None), umr_sum=numpy.core._methods.umr_sum):
AttributeError: 'module' object has no attribute 'umr_sum'

Do you know how I can fix this?

**Comment by mehrdadn** [comment]
Hi! Which operating system and version of NumPy are you using?

You can print the version via `import numpy; print(numpy.__version__)`

**Comment by lim643** [comment]
Mac OS and version 1.8.0rc1

**Comment by mehrdadn** [comment]
Ah okay thanks. Most likely they've changed the internal bits of NumPy that I had been calling directly. I'll try to fix it and provide an update if/when I do, but in the meantime, you can try downgrading to an earlier version of NumPy to see if it works. (I haven't tested on Mac, but on my system it works on 1.16.3, for example.)

**Comment by lim643** [comment]
Great, thanks so much for replying so quickly!

**Comment by mehrdadn** [comment]
Yup!

**Comment by mehrdadn** [comment]
Also sorry I misspoke -- I meant downgrading NumPy, not Python. (Edited)

**Comment by lim643** [comment]
Got it

**Comment by mehrdadn** [comment]
I pushed a fix, see if that works?
(There's still an incompatibility with `fftpack_lite` in Python 3's NumPy having changed, but it may not affect you.)

**Comment by lim643** [comment]
I ran the program using both NumPy 1.17.0 and 1.16.3, using the line:
python3 Main.py --source=65280072.0 --dest=65345534.0 --budget=1800 --network="data/sf.osm.json"

I think it worked for the given time budget since it displayed that it was calculating and that it got a result, but then it displayed an error when calculating for other time budgets.

Main.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Importing numpy... 109 ms
Importing scipy.special... 149 ms
Importing numba... 0 ms
Other imports... 27 ms
Reading network... 498 ms
Loading network... 22 ms
Computing minimum travel times... 511 ms
Initializing vertices and edges... 228 ms
Routing from #16 to #3008 with budget T = 1800.0/0.1379952166717165 = 13044 steps...
Computing memory requirements... 195 ms
Pre-allocating buffers (if requested)... 327 ms
Computing optimal update order... 3531 ms
Updated node to t = 12.14 seconds = 88 steps (0.0% complete, inf/inf compute sec remaining)
Updated node to t = 553.22 seconds = 4009 steps (4.2% complete, 98.8/103.2 compute sec remaining)
Updated node to t = 628.84 seconds = 4557 steps (8.5% complete, 56.3/61.5 compute sec remaining)
Updated node to t = 683.35 seconds = 4952 steps (12.7% complete, 43.3/49.6 compute sec remaining)
Updated node to t = 727.10 seconds = 5269 steps (17.0% complete, 34.7/41.8 compute sec remaining)
Updated node to t = 766.56 seconds = 5555 steps (21.2% complete, 29.3/37.2 compute sec remaining)
Updated node to t = 801.89 seconds = 5811 steps (25.5% complete, 25.7/34.4 compute sec remaining)
Updated node to t = 834.73 seconds = 6049 steps (29.7% complete, 22.8/32.4 compute sec remaining)
Updated node to t = 867.44 seconds = 6286 steps (33.9% complete, 20.5/31.0 compute sec remaining)
Updated node to t = 897.93 seconds = 6507 steps (38.2% complete, 18.5/29.9 compute sec remaining)
Updated node to t = 928.16 seconds = 6726 steps (42.4% complete, 16.8/29.1 compute sec remaining)
Updated node to t = 960.03 seconds = 6957 steps (46.7% complete, 15.2/28.5 compute sec remaining)
Updated node to t = 991.63 seconds = 7186 steps (50.9% complete, 13.7/28.0 compute sec remaining)
Updated node to t = 1022.82 seconds = 7412 steps (55.2% complete, 12.3/27.5 compute sec remaining)
Updated node to t = 1054.97 seconds = 7645 steps (59.4% complete, 11.0/27.0 compute sec remaining)
Updated node to t = 1089.33 seconds = 7894 steps (63.6% complete, 9.7/26.6 compute sec remaining)
Updated node to t = 1126.32 seconds = 8162 steps (67.9% complete, 8.4/26.3 compute sec remaining)
Updated node to t = 1165.23 seconds = 8444 steps (72.1% complete, 7.2/25.9 compute sec remaining)
Updated node to t = 1210.91 seconds = 8775 steps (76.4% complete, 6.1/25.7 compute sec remaining)
Updated node to t = 1254.51 seconds = 9091 steps (80.6% complete, 4.9/25.3 compute sec remaining)
Updated node to t = 1303.36 seconds = 9445 steps (84.8% complete, 3.8/25.0 compute sec remaining)
Updated node to t = 1353.73 seconds = 9810 steps (89.1% complete, 2.7/24.8 compute sec remaining)
Updated node to t = 1417.49 seconds = 10272 steps (93.3% complete, 1.6/24.7 compute sec remaining)
Updated node to t = 1506.22 seconds = 10915 steps (97.6% complete, 0.6/24.7 compute sec remaining)
Policy: 0.877833240124769
Policy time: 25.974594079 seconds
Found new path for tibudget = 13044; examining other time budgets...
Traceback (most recent call last):
  File "Main.py", line 698, in <module>
    raise SystemExit(main(*sys.argv))
  File "Main.py", line 656, in main
    pipe.send(True)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by lim643** [comment]
Also, I'm running your program only on Terminal, so I don't have the OpenStreetMap visual you use on your README. Could you explain to me what the outputs mean (i.e. Policy, Policy time)?

**Comment by mehrdadn** [comment]
Thanks for reporting these! I pushed a few fixes that should resolve these. Try pulling again.  
For the visualization, try `python3 -m pip install pyglet`.  

The "Policy time" just shows how long it took to compute the policy (and similarly with Path time).  
If it's taking a long time, you might get a speedup with `python3 -m pip install scipy numba`.

You can also experiment with changing `multiprocess = False` to `multiprocess = True` in `main()` to do the computation and visualization in parallel, and changing `gui_update_interval_sec = 1. / 25` to `gui_update_interval_sec = 1. / 60` for a smoother animation (which has less of an impact when the two are in parallel).

Let me know if you run into any other issues or have more questions!

**Comment by lim643** [comment]
It worked perfectly! Thank you so much for taking the time to look at this and help me, I really appreciate it.

**Comment by mehrdadn** [comment]
Awesome, happy to!

**Comment by mehrdadn** [comment]
I also pushed some more updates that should speed things up. :)

**Comment by mehrdadn** [comment]
Just a note, I discovered a bug in my latest updates here. When I was trying to fix the missing-`fftpack_lite` incompatibility, I missed undoing the normalization after switching to `numpy.fft.irfft`, so my FFTs were way off in that case. It might not have affected you (depending on which FFT module you were using), but just wanted to let you know about it in case it did. The updated version should be fixed, hopefully.
